-- Explore All Objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES

-- Explore ALL Columns IN THE Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS

-- Explore ALL Countries our customers come from.
SELECT DISTINCT country FROM gold.dim_customers

-- Explore ALL Categories "The major divisions"
SELECT DISTINCT category,sub_category,product_name FROM gold.dim_products
ORDER BY 1,2,3

-- Find the date of the first and last order
-- How many years of sales are avaiable
SELECT
MIN(order_date) as first_order_date,
MAX(order_date) as last_order_date,
DATEDIFF(month, MIN(order_date), MAX(order_date)) AS order_range_months
FROM gold.fact_sales

--Find the youngest and the oldest customer
SELECT
MIN(birthdate) as oldest_birthdate,
DATEDIFF(year, MIN(birthdate), GETDATE()) AS oldest_age,
MAX(birthdate) as youngest_birthdate,
DATEDIFF(year, MAX(birthdate), GETDATE()) as youngest_age
FROM gold.dim_customers

-- Find the Total sales
SELECT SUM(sales_amount) as total_sales FROM gold.fact_sales

-- Find how many items are sold
SELECT SUM(quantity) as total_quantity FROM gold.fact_sales

-- Find the average selling price
SELECT AVG(sls_price) as avg_selling_price FROM gold.fact_sales

-- Find the Total number of Orders
SELECT COUNT(DISTINCT order_number) as total_orders FROM gold.fact_sales

-- Find the Total number of Products
SELECT COUNT(DISTINCT product_key) as total_products FROM gold.dim_products

-- Find the total number of customers
SELECT COUNT(customer_key) as total_customers FROM gold.dim_customers

-- Find the total number of customers placed an order
SELECT COUNT(DISTINCT customer_key) AS total_orders_placed FROM gold.fact_sales

-- Generate a Report that shows all the key metrics of the business

SELECT 'Total Sales' AS measure_name, SUM(sales_amount) as measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity)  FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total Order', COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total Products', COUNT(DISTINCT product_key) FROM gold.dim_products
UNION ALL
SELECT 'Total Customers', COUNT(customer_key) FROM gold.dim_customers


-- Find the total customers by countries
SELECT
country,
COUNT(customer_key) as total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find the total customeres by gender
SELECT
gender,
COUNT(customer_key) as total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find the total products by category
SELECT 
category,
COUNT(product_key) as total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average costs in each category?
SELECT
category,
AVG(cost) as average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC

-- What is the total revenue generated for each category?
SELECT
p.category,
SUM(f.sales_amount) as total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products as p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue  DESC


-- Find the total revenue is generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) as total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC



-- What is the distribution of sold items across countries?

SELECT
c.country,
SUM(f.quantity) as total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.country
ORDER BY total_sold_items DESC

--  Which 5 products generate the highest revenue?

SELECT TOP 5
p.product_name,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC

--  What are the 5 worst-performing products in terms of sales?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC